root: true

env:
  node: true

extends:
  - eslint:recommended
  - prettier

overrides:
  - files: ['**/*.ts']
    parser: '@typescript-eslint/parser'
    extends:
      - plugin:@typescript-eslint/recommended
      - prettier/@typescript-eslint
    plugins:
      - '@typescript-eslint'

    rules:
      no-var: 'off'

      '@typescript-eslint/explicit-function-return-type':
        - warn
        - allowExpressions: true
      '@typescript-eslint/no-namespace': 'off'
